/** Declaration file generated by dts-gen */

export = slime_validator;

declare class slime_validator {
    constructor(...args: any[]);

    validate(...args: any[]): void;

    static usePlugin(plugin: any, replace: any): void;

    static validate(schema: any, target: any): any;

}

